<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Application_Layer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wishlist.Domain\Wishlist.Domain.csproj" />
  </ItemGroup>

</Project>
